# Generated by Django 2.2.6 on 2019-10-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
    ]
